### ISSUE TITLE
Create vault from cli and add files to it.

### ISSUE THREAD

**Issue by qwertz22** [cryptomator/cli#31]
Hello,

my most desired feature is to create vaults from cli and add files into it. That would be the most useable feauture for me and I'm sure for a lot of people, too.

Nochmal auf Deutsch:
Das geilste Feature wäre es, über die Kommandozeile Tresore zu kreieren und auch Dateien hinzuzufügen, damit ich einiges automatisieren könnte. Sicherlich würden dieses Feature auch viele andere feiern.

Regards und so.

**Comment by andreiled** [comment]
It would also be useful if CLI could be used to mount unlocked vault using FUSE/Dokany.
For example, I am looking for a file encryption solution that I could run on a headless server.

**Comment by yiyangc91** [comment]
This seems to already work?

I can run java -jar cli.jar --vault newVault=/some/new/folder --fusemount newVault=/mnt/xxx and it will happily create a new vault for me.

**Comment by JackHewson** [comment]
> my most desired feature is to create vaults from cli and add files into it. That would be the most useable feauture for me and I'm sure for a lot of people, too.

Tested with https://github.com/cryptomator/cli/releases/tag/0.5.1 I want to confirm, that it's not possible to **create a new vault:**

```
java -jar cryptomator-cli-0.5.1.jar --vault newVault=C:/temp/test --bind 127.0.0.1 --port 8080
```

This results in:

```
Exception in thread "main" java.nio.file.NoSuchFileException: C:\temp\test\vault.cryptomator
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
```

There must be an existing vault in the given directory.

**Comment by cfitz25** [comment]
Any updates on this? This is the only thing stopping me from using cryptomator right now

**Comment by geosmart** [comment]
> > my most desired feature is to create vaults from cli and add files into it. That would be the most useable feauture for me and I'm sure for a lot of people, too.
> 
> Tested with [`0.5.1` (release)](https://github.com/cryptomator/cli/releases/tag/0.5.1) I want to confirm, that it's not possible to **create a new vault:**
> 
> ```
> java -jar cryptomator-cli-0.5.1.jar --vault newVault=C:/temp/test --bind 127.0.0.1 --port 8080
> ```
> 
> This results in:
> 
> ```
> Exception in thread "main" java.nio.file.NoSuchFileException: C:\temp\test\vault.cryptomator
>         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
>         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
>         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
>         at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
> ```
> 
> There must be an existing vault in the given directory.

+1

if I use a vault created by the UI, it's also work by cli.

but how to totaly init a new vault by cli?

**Comment by Spickles89** [comment]
Hi everyone, has there been any updates to this issue? I wanted to bump this issue to the forefront since I too would really like to be able to create/open/lock vaults using the Cryptomator CLI. I'm finding the CLI help section lacking (using the "cryptomator-cli --help" command yields very few options).

**Comment by Jonathans859** [comment]
Honestly I'd also welcome a feature to create new vaults, especially because the GUI is inaccessible for my screen reader and the CLI is the best way to use this for now. Any updates on this?
