### ISSUE TITLE
Bug: fatal error when running on arm device?

### ISSUE THREAD

**Issue by WuShufei** [cryptomator/cli#55]
I've tried to get the jar to load with every combination of arguments, and having fuse-mounted the chosen directory beforehand or not.  The error continues the same regardless.

`15:30:57.257 [main] INFO  o.c.frontend.webdav.WebDavServer - Binding server socket to 127.0.0.1:8080
15:30:57.338 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@b729e6{HTTP/1.1, (http/1.1)}{127.0.0.1:8080}
15:30:57.349 [main] INFO  org.eclipse.jetty.server.Server - jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 19.0.2+7
15:30:57.549 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@a664f2{/,null,AVAILABLE}
15:30:57.588 [main] INFO  org.eclipse.jetty.server.Server - Started Server@67f029{STARTING}[10.0.6,sto=0] @1965ms
15:30:57.589 [main] INFO  o.c.frontend.webdav.WebDavServer - WebDavServer started.
15:30:57.589 [main] INFO  org.cryptomator.cli.frontend.WebDav - WebDAV server started: 127.0.0.1:8080
15:30:57.639 [main] INFO  org.cryptomator.cli.CryptomatorCli - Unlocking vault "cccliVault" located at /home/synergy/CCLI2NextCloud
15:30:57.640 [main] INFO  o.c.c.p.PasswordFromPropertyStrategy - Vault 'cccliVault' password from property.
Exception in thread "main" java.nio.file.NoSuchFileException: /home/test/vault.cryptomator
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3287)
	at java.base/java.nio.file.Files.readString(Files.java:3365)
	at org.cryptomator.cryptofs.CryptoFileSystems.readVaultConfigFile(CryptoFileSystems.java:113)
	at org.cryptomator.cryptofs.CryptoFileSystems.create(CryptoFileSystems.java:49)
	at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:194)
	at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:86)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:126)
	at org.cryptomator.cli.CryptomatorCli.startup(CryptomatorCli.java:101)
	at org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:43)
`

Device is a Raspberry Pi 4B inside a Raspad 3 running Raspbian 64.
`OS: Raspbian GNU/Linux 10 (buster) armv7l 
Host: Raspberry Pi 4 Model B Rev 1.4 
Kernel: 5.10.103-v7l+ 
Uptime: 2 hours, 25 mins 
Packages: 4370 (dpkg), 6 (flatpak), 9 (snap) 
Shell: bash 5.0.3 
Resolution: 1280x800 
DE: LXDE 
WM: Openbox 
Theme: Adwaita-dark [GTK2/3] 
Icons: PiXflat [GTK2/3] 
Terminal: guake 
CPU: BCM2711 (4) @ 1.600GHz 
Memory: 1709MiB / 7720MiB 
`
Java info (yes, I got OpenJDK 19 running on it):
`Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 19.0.2, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/jdk-19.0.2+7
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.103-v7l+", arch: "arm", family: "unix"
`
Thanks for any info!

**Comment by WuShufei** [comment]
Is this the same issue?  The CLI jar cannot create vaults?  Since the GUI also cannot compile (that I've yet found) on arm devices, this is a basic issue.
[https://github.com/cryptomator/cli/issues/31](url)

**Comment by WuShufei** [comment]
Is this the same issue?  The CLI jar cannot create vaults?  Since the GUI also cannot compile (that I've yet found) on arm devices, this is a basic issue.
[Issue 31](https://github.com/cryptomator/cli/issues/31)

**Comment by needsupport** [comment]
Any update eon this issue ? Please resolve this

**Comment by ccchan234** [comment]
who will use ctmt? no support.

**Comment by infeo** [comment]
@ccchan234 Please do not post content unrelated to the issue. You can share your personal opinion in the Cryptomator forum.

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
