### ISSUE TITLE
Not working with 3 Mounters

### ISSUE THREAD

**Issue by gomble** [cryptomator/cli#74]
It does not work, tested 3 mounters:

```
root@paperless-ngx:~/cryptomator-cli/bin# ./cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider --mountPoint=/root/cryptomator-tresor/ /root/One
Drive/
Enter value for --password:stdin (Passphrase, read from STDIN): 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no fuse3 in java.library.path: :/root/cryptomator-cli/lib/app:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at org.cryptomator.jfuse.linux.amd64@0.7.0/org.cryptomator.jfuse.linux.amd64.LinuxFuseBuilder.build(LinuxFuseBuilder.java:42)
        at org.cryptomator.frontend.fuse@5.0.2/org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider$LinuxFuseMountBuilder.mount(LinuxFuseMountProvider.java:123)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.MountSetup.mount(MountSetup.java:119)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:86)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)
root@paperless-ngx:~/cryptomator-cli/bin# ./cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.webdav.mount.LinuxGioMounter --mountPoint=/root/cryptomator-tresor/ /root/OneDrive
/
Enter value for --password:stdin (Passphrase, read from STDIN): 
java.lang.UnsupportedOperationException
        at org.cryptomator.integrations.api@1.4.0/org.cryptomator.integrations.mount.MountBuilder.setMountpoint(MountBuilder.java:62)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.MountSetup.mount(MountSetup.java:117)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:86)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)
root@paperless-ngx:~/cryptomator-cli/bin# ./cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.webdav.mount.FallbackMounter --mountPoint=/root/cryptomator-tresor/ /root/OneDrive
/
Enter value for --password:stdin (Passphrase, read from STDIN): 
java.lang.UnsupportedOperationException
        at org.cryptomator.integrations.api@1.4.0/org.cryptomator.integrations.mount.MountBuilder.setMountpoint(MountBuilder.java:62)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.MountSetup.mount(MountSetup.java:117)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:86)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)
```

**Comment by gomble** [comment]
ok solved with: 
apt install fuse3

:)
