### ISSUE TITLE
Does not work when "current working directory" is different from where executable is

### ISSUE THREAD

**Issue by mhogomchungu** [cryptomator/cli#82]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cli/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cli/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

cryptomator-cli does not run when started from a folder that is different from where the executable is.

### What software is involved?

- Operating System: Linux
- Cryptomator CLI: 0.6.0

### Volume Type

FUSE

### Steps to Reproduce

1. Open terminal and change directory to somewhere far from where cryptomator-cli is.
2. Run cryptomator-cli from from far away distance.

### Expected Behavior

crytomator-cli to work as expected.

### Actual Behavior

Fails to run and complain about "too many open files".

### Reproducibility

Always

### Relevant Log Output

```shell
[ink@localhost ~]$ cryptomator-cli/bin/cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider --mountPoint=bbb aaa
Enter value for --password:stdin (Passphrase, read from STDIN): 
java.nio.file.FileSystemException: aaa/vault.cryptomator: Too many open files
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.readAllBytes(Unknown Source)
        at java.base/java.nio.file.Files.readString(Unknown Source)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.readConfigFromStorage(Unlock.java:122)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:77)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)
[ink@localhost ~]$
```

**Comment by infeo** [comment]
The actual error is a little bit hidden:
> at org.cryptomator.cli@0.6.0-beta1/org.cryptomator.cli.Unlock.readConfigFromStorage(Unlock.java:122)

Cryptomator CLI could not open the file descriptor to the vault config file. This is a configuration error on your system, not a bug in Cryptomator CLI. I suggest to search the web for the error "Too many open files" and how to resolve it.

**Comment by mhogomchungu** [comment]
Did you try it and it worked on your system or you are responding only from looking at the reported log?

When i run with with the "wrong" current working directory, it hangs for a few seconds and CPU going to 100% when its hung and then it reports the error i posted. I suspect the problem is caused by cryptomator going in  a busy loop looking using opening files without closing them and it ends up using all available file handles and then it errors out.

I see this on my normal linux environment and in a kde flatpak environment.

When i run it from "correct" current work directory with a vault path that does not exist, it correctly fails immediately with below error.

```
./cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider --mountPoint=bbb aaa
Enter value for --password:stdin (Passphrase, read from STDIN): 
java.nio.file.NoSuchFileException: aaa/vault.cryptomator
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.readAllBytes(Unknown Source)
        at java.base/java.nio.file.Files.readString(Unknown Source)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.readConfigFromStorage(Unlock.java:122)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.call(Unlock.java:77)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)
[ink@localhost bin]$ 

```

When i run it from "correct" current working directory but mount point does not exist, it errors out immediately with below error
```
[ink@localhost bin]$ ./cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider --mountPoint=bbb /home/ink/.vaults/cryptomator
Enter value for --password:stdin (Passphrase, read from STDIN): 


java.lang.IllegalArgumentException: mount point must be an existing directory
        at org.cryptomator.frontend.fuse@5.0.2/org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider$LinuxFuseMountBuilder.setMountpoint(LinuxFuseMountProvider.java:108)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.MountSetup.mount(MountSetup.java:120)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.call(Unlock.java:86)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)
[ink@localhost bin]$ 

```

**Comment by infeo** [comment]
> Did you try it and it worked on your system 

Yes. On my VM running Fedora 40 with kernel 6.12.4. Also on my Ubuntu VM running Ubunto 24.04 with kernel 6.8.0. Your system restricts the number of open file handles when accessing from a different directory, you have to resolve this.

**Comment by mhogomchungu** [comment]
>Your system restricts the number of open file handles when accessing from a different directory, you have to resolve this
```
[ink@localhost ~]$ ulimit -n
1024
[ink@localhost ~]$ 
```

Would appreciate if you could post the full command you used when testing.

I have a project called [SiriKali](https://mhogomchungu.github.io/sirikali/) and it added support for cryptomator-cli 0.6.0 and my concern is not with my own system only but with all supported systems.

https://flathub.org/apps/io.github.mhogomchungu.sirikali
https://github.com/mhogomchungu/sirikali/releases/tag/1.8.0

**Comment by infeo** [comment]
Here ya go:
```
[john@dough /]$ /home/john/Downloads/cryptomator-cli-0.6.0-linux-x64/target/cryptomator-cli/bin/cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider --mountPoint=/home/john/mnt /home/john/asd/
```

Note, that in the end the cli tool uses the linux calls open/openat and just hands back the error code. So you should investigate possible causes for [EMFILE](https://man7.org/linux/man-pages/man3/errno.3.html#:~:text=EMFILE).

**Comment by mhogomchungu** [comment]
Using full path works for me too.

Try with relative path to the executable.


```
/home/ink/.var/app/io.github.mhogomchungu.sirikali/data/SiriKali/bin/cryptomator-cli/bin/cryptomator-cli unlock --password:stdin --mounter=org.cryptomator.frontend.fuse.mount.LinuxFuseMountProvider --verbose --mountPoint=bbb /home/ink/.vaults/cryptomator
Enter value for --password:stdin (Passphrase, read from STDIN): 
[main] DEBUG o.c.c.CryptomatorCli - Activated debug logging 
[main] DEBUG o.c.cli.Unlock - Reading vault config from file /home/ink/.vaults/cryptomator/vault.cryptomator. 


org.cryptomator.cryptolib.api.InvalidPassphraseException
        at org.cryptomator.cryptolib@2.2.0/org.cryptomator.cryptolib.common.MasterkeyFileAccess.unlock(MasterkeyFileAccess.java:147)
        at org.cryptomator.cryptolib@2.2.0/org.cryptomator.cryptolib.common.MasterkeyFileAccess.load(MasterkeyFileAccess.java:131)
        at org.cryptomator.cryptolib@2.2.0/org.cryptomator.cryptolib.common.MasterkeyFileAccess.load(MasterkeyFileAccess.java:119)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.loadMasterkey(Unlock.java:107)
        at org.cryptomator.cryptofs@2.7.1/org.cryptomator.cryptofs.CryptoFileSystems.create(CryptoFileSystems.java:53)
        at org.cryptomator.cryptofs@2.7.1/org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:196)
        at org.cryptomator.cryptofs@2.7.1/org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:86)
        at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at org.cryptomator.cryptofs@2.7.1/org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:126)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.call(Unlock.java:85)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.Unlock.call(Unlock.java:25)
        at info.picocli@4.7.6/picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at info.picocli@4.7.6/picocli.CommandLine.access$1500(CommandLine.java:148)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at info.picocli@4.7.6/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at info.picocli@4.7.6/picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.CryptomatorCli.executionStrategy(CryptomatorCli.java:31)
        at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2174)
        at org.cryptomator.cli@0.6.0/org.cryptomator.cli.CryptomatorCli.main(CryptomatorCli.java:49)

```

**Comment by infeo** [comment]
Also when using relative paths the app works.

**Comment by infeo** [comment]
By any chance, are you running the cli from a flatpak? Since Flatpaks are sandboxed, this is very high probability the issue and you have to ask the flatpak community about the problem.
